import {expect,test,type Page} from "@playwright/test";
import {resolve} from "node:path";
import {pathToFileURL} from "node:url";
import sharp from "sharp";
import {mkdir} from "node:fs/promises";
import {createServer} from "node:http";
import type {AddressInfo} from "node:net";
import type {createLocalChatServer as Factory} from "../../src/server/local-chat-server";
import {emptySpeakerProfile} from "../../src/shared/expression";
import {emptyCreativeDraft} from "../../src/client/UnifiedExpression";
import {openCreate,openCreationOptions,holdCreationReview} from "../expression-ui";
let app:Awaited<ReturnType<typeof Factory>>,origin:string,imageBodies:string[],analysisInputs:Record<string,unknown>[];
let holdImage=false,failImage=false,releaseImage:(()=>void)|undefined;
const root=process.env.VISUAL_BUILD_ROOT??"dist",built=(file:string)=>pathToFileURL(resolve(root,"server",file)).href;
test.beforeEach(async()=>{
  imageBodies=[];analysisInputs=[];holdImage=false;failImage=false;releaseImage=undefined;
  const {createLocalChatServer}:{createLocalChatServer:typeof Factory}=await import(built("local-chat-server.js"));
  const {ongoingPersonalGenerationOptions}=await import(built("personal-image.js"));
  const {localPaidLease}=await import(built("local-generation-config.js"));
  expect(localPaidLease.busy).toBe(false);localPaidLease.nextAt=0;localPaidLease.providerNextAt=0;
  const image=await sharp({create:{width:1024,height:1024,channels:3,background:"#8171b3"}})
    .composite([{input:Buffer.from('<svg width="1024" height="1024"><circle cx="320" cy="360" r="160" fill="#f8d880"/><rect x="610" y="620" width="240" height="200" fill="#66bbaa"/></svg>')}]).png().toBuffer();
  app=await createLocalChatServer("OFFLINE-EXPRESSION-TEST",{
    clientRoot:resolve(root,"client"),interaction:"direct-personal",catalogSource:"original-demo",cooldownMs:0,
    generation:{...ongoingPersonalGenerationOptions(),transport:async(_url,init)=>{
      imageBodies.push(String(init?.body));
      if(holdImage)await new Promise<void>(resolve=>{const timer=setTimeout(resolve,30_000);releaseImage=()=>{clearTimeout(timer);resolve();};});
      if(failImage)return new Response("",{status:503});
      return new Response(JSON.stringify({data:[{b64_json:image.toString("base64")}]}),{headers:{"Content-Type":"application/json"}});
    }},
    transport:async(_url,init)=>{
      const payload=JSON.parse(JSON.parse(String(init?.body)).messages[1].content[0].text);analysisInputs.push(payload);
      return new Response(JSON.stringify({choices:[{finish_reason:"stop",message:{content:JSON.stringify(payload.task==="rank"?{
        candidates:payload.catalog.slice(0,3).map((a:{id:string})=>({id:a.id,reason:"Fixture report-aware reason",caution:"No certainty"}))
      }:{background:{source:null,context:null,frames:[]},observations:[{text:"Original visual fixture",frames:payload.frames.map((f:{id:string})=>f.id)}],commonUsage:["Uncertain"],contextualInterpretations:[{text:"Possible only",context:payload.context.map((c:{label:string})=>c.label)}],
        uncertainties:["Not actual intent"],safeResponseGuidance:["Ask"]})}}]}));
    }
  });origin=await app.start(0);
});
test.afterEach(async()=>{releaseImage?.();await app.close();});
async function open(page:Page){
  await page.setViewportSize({width:1440,height:900});await page.goto(origin+"/chat");
  await page.getByLabel("Language / 语言").selectOption("en");
  await expect(page.getByRole("button",{name:"Start a demo conversation",exact:true})).toBeEnabled();
}
async function api(page:Page,path:string,body:object={}){
  return page.evaluate(async({path,body})=>{
    const session=await (await fetch("/local/session",{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"})).json();
    const payload=["speaker","generation/process","generation/status","state","reset"].includes(path)?body:{revision:session.revision,...body};
    const r=await fetch("/local/"+path,{method:"POST",headers:{"Content-Type":"application/json","X-Local-CSRF":session.csrf},body:JSON.stringify(payload)});
    return {status:r.status,value:await r.json()};
  },{path,body});
}
test("fresh English UI, demo and all shared expression contexts use the latest ten without removing history",async({page})=>{
  await page.goto(origin+"/chat");
  await expect(page.locator("html")).toHaveAttribute("lang","en");
  await expect(page.getByLabel("Language / 语言")).toHaveValue("en");
  await page.getByRole("button",{name:"Start a demo conversation",exact:true}).click();
  await expect(page.getByTestId("chat-message")).toHaveCount(5);
  await expect(page.getByTestId("chat-message").first()).toContainText("Proposal: one portal");
  for(let i=5;i<14;i++)await api(page,"message",{speaker:"Alex",text:`Original context ${i}`});
  await api(page,"speaker/profile",{speaker:"Alex",profile:{...emptySpeakerProfile(),language:"zh-CN",tone:"Voluntary preference, not ethnicity"}});
  await page.reload();
  await page.locator(".local-composer").getByRole("button",{name:"Help me express",exact:true}).click();
  await page.getByLabel("What would you like to express?",{exact:true}).fill("保留原文，不翻译");
  const reviewed=page.waitForResponse(r=>new URL(r.url()).pathname==="/local/review");
  await page.getByRole("button",{name:"Review selected content",exact:true}).click();
  const review=await (await reviewed).json();
  expect(review.input.context).toHaveLength(10);
  expect(review.input.context[0].text).toBe("Alex: Let's start with just the dashboards.");
  await page.getByRole("button",{name:"Recommend expressions",exact:true}).click();
  await expect(page.locator(".local-candidate")).toHaveCount(3);
  expect(analysisInputs[0]).toMatchObject({intent:"保留原文，不翻译",preferences:{outputLanguage:"en"},speakerContext:{profile:{language:"zh-CN"}}});
  expect(analysisInputs[0].context).toHaveLength(10);
  await openCreate(page,"en",false);
  await expect(page.getByLabel("What would you like to express?",{exact:true})).toHaveValue("保留原文，不翻译");
  await page.getByRole("button",{name:"Generate image",exact:true}).click();
  await expect(page.getByText("Output ready for your inspection",{exact:true})).toBeVisible();
  const data=JSON.parse(JSON.parse(imageBodies[0]).prompt.split("\n").at(-1));
  expect(data).toMatchObject({intent:"保留原文，不翻译",requesterOrAudiencePreferences:{language:"en"},speakerContext:{profile:{language:"zh-CN"}}});
  expect(data.context).toHaveLength(10);expect(data.context.map((c:{text:string})=>c.text)).toEqual(review.input.context.map((c:{text:string})=>c.text));
  await expect(page.getByTestId("chat-message")).toHaveCount(14);
  expect(analysisInputs).toHaveLength(1);expect(imageBodies).toHaveLength(1);
});
test("all standalone APIs reject eleven included messages before dispatch and preserve bounded excluded edits",async({page})=>{
  await open(page);
  for(let i=0;i<14;i++)await api(page,"message",{speaker:"Maya",text:`Original ${i}${i===0?" 😊":""}`});
  const state=(await api(page,"state")).value;
  const context=state.messages.slice(0,12).map((m:{id:string;text:string},i:number)=>({label:m.id,text:m.text,timestamp:"",included:i<11}));
  const input={version:0,intent:"An original reply",context,preferences:{source:"requester-reported",confirmed:true,outputLanguage:"en",familiarity:"",formality:"unknown",relationship:"",humor:"",avoid:""}};
  for(const command of ["explainVisual","recommendVisual"]){
    const rejected=await api(page,"review",{command,selectedId:state.messages[0].id,input});
    expect(rejected.status).toBe(400);expect(rejected.value.code).toBe("local-context-limit");
  }
  const draft={...emptyCreativeDraft("en"),intent:"A fictional response",context:context.map(({label,text,included}:{label:string;text:string;included:boolean})=>({label,text,included}))};
  const rejected=await api(page,"generation/review",{draft,draftRevision:0});
  expect(rejected.status).toBe(400);expect(rejected.value.code).toBe("local-context-limit");
  expect(analysisInputs).toHaveLength(0);expect(imageBodies).toHaveLength(0);
  context[10].included=false;context[10].text="EXCLUDED EDIT KEPT";
  draft.context[10].included=false;draft.context[10].text="EXCLUDED EDIT KEPT";
  const valid=(await api(page,"review",{command:"explainVisual",selectedId:state.messages[0].id,input})).value;
  expect(valid.input.context).toHaveLength(12);expect(valid.input.context[10].text).toBe("EXCLUDED EDIT KEPT");
  const result=await api(page,"process",{digest:valid.processing.digest,consent:true});
  expect(result.status).toBe(200);expect(analysisInputs[0].context).toHaveLength(10);
  expect(JSON.stringify(analysisInputs[0])).not.toContain("EXCLUDED EDIT KEPT");
  const generated=(await api(page,"generation/review",{draft,draftRevision:1})).value;
  expect(JSON.parse(generated.prompt.split("\n").at(-1)).context).toHaveLength(10);
  expect(generated.prompt).not.toContain("EXCLUDED EDIT KEPT");
  expect((await api(page,"state")).value.messages).toHaveLength(14);
  expect(imageBodies).toHaveLength(0);
});
for(const [language,description] of [
  ["zh-CN","结合电影角色"],
  ["zh-CN","福尔摩斯和华生发现问题后的得意表情，用来庆祝排查成功"],
  ["en","Sherlock Holmes and Watson looking pleased after solving a problem"]
] as const)test(`simple creation ${language}: ${description}`,async({page})=>{
  const t=(en:string,zh:string)=>language==="en"?en:zh;
  await open(page);
  await api(page,"message",{speaker:"Maya",text:"Our fictional investigation succeeded."});
  await api(page,"speaker/profile",{speaker:"Alex",profile:{...emptySpeakerProfile(),language,tone:"Quiet shared celebration"}});
  await page.reload();await page.getByLabel("Language / 语言").selectOption(language);
  await openCreate(page,language,false);
  const intent=page.getByLabel(t("What would you like to express?","你想表达什么？"),{exact:true});
  await intent.fill(description);
  await page.getByRole("radio",{name:t("Find an existing image","推荐现成图"),exact:true}).check();
  await expect(intent).toHaveValue(description);
  await page.getByRole("radio",{name:t("Create a new image","生成新图"),exact:true}).check();
  await expect(intent).toHaveValue(description);
  const panel=page.locator(".local-copilot-content");
  await expect(panel.getByRole("textbox")).toHaveCount(1);
  await expect(page.getByLabel(t("Creative description","创作描述"),{exact:true})).not.toBeVisible();
  await expect(page.getByLabel(t("Expression style","表达风格"),{exact:true})).not.toBeVisible();
  await expect(page.getByLabel(t("Expression intensity","表达强度"),{exact:true})).toHaveValue("auto");
  await expect(page.locator(".creation-advanced > summary")).toContainText(t("Saved speaker preferences","已保存的发言者偏好"));
  await expect(page.getByRole("button",{name:t("Confirm creative idea","确认创作内容"),exact:true})).toHaveCount(0);
  await page.getByLabel(t("Requested output","期望输出"),{exact:true}).selectOption("gif");
  await expect(page.getByRole("button",{name:t("Generate GIF","生成 GIF"),exact:true})).toBeEnabled();
  await page.getByLabel(t("Requested output","期望输出"),{exact:true}).selectOption("image");
  await page.setViewportSize({width:320,height:900});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  expect(imageBodies).toHaveLength(0);expect(analysisInputs).toHaveLength(0);
  const reviewed=page.waitForResponse(r=>new URL(r.url()).pathname==="/local/generation/review");
  const processed=page.waitForRequest(r=>new URL(r.url()).pathname==="/local/generation/process");
  await page.getByRole("button",{name:t("Generate image","生成图片"),exact:true}).click();
  const review=await (await reviewed).json();
  expect((await processed).postDataJSON()).toMatchObject({operationId:review.operationId,digest:review.digest,consent:true});
  await expect(page.getByText(t("Output ready for your inspection","输出等待你检查"),{exact:true})).toBeVisible();
  expect(imageBodies).toEqual([review.body]);
  const prompt=JSON.parse(imageBodies[0]).prompt,data=JSON.parse(prompt.split("\n").at(-1));
  expect(data).toMatchObject({intent:description,creative:"",expression:{style:"auto",intensity:"auto",reference:""},
    context:[{text:"Maya: Our fictional investigation succeeded."}],speakerContext:{role:"outgoing-speaker",profile:{tone:"Quiet shared celebration"}}});
  expect(prompt).not.toContain("Do not copy recognizable copyrighted characters");
  expect(prompt).toContain("Preserve multiple characters when requested");
  await expect(page.getByRole("button",{name:t("Preview generated insertion","预览生成内容插入"),exact:true})).toBeEnabled();
});
test("optional creation choices stay visible in summary and reset without losing intent, output or saved profiles",async({page})=>{
  await open(page);await openCreate(page);
  await page.getByLabel("What would you like to express?",{exact:true}).fill("An original design for Sherlock Holmes celebrating.");
  await page.getByLabel("Creative description",{exact:true}).fill("Keep a tiny lantern");
  await page.getByLabel("Expression style",{exact:true}).selectOption("deadpan-animal");
  await page.getByLabel("Expression intensity",{exact:true}).selectOption("exaggerated");
  await page.getByLabel("Requested output",{exact:true}).selectOption("gif");
  await page.locator(".speaker-profile summary").click();
  await page.getByLabel("Speaker humor",{exact:true}).fill("Gentle humor");
  await page.getByRole("button",{name:"Save speaker profile",exact:true}).click();
  await expect(page.locator(".speaker-profile summary")).toContainText("self-reported");
  const summary=page.locator(".creation-advanced > summary");
  await summary.click();await expect(summary).toContainText("Keep a tiny lantern");await expect(summary).toContainText("Exaggerated");
  await page.getByRole("radio",{name:"Find an existing image",exact:true}).check();
  await page.getByRole("radio",{name:"Create a new image",exact:true}).check();
  await expect(summary).toContainText("Keep a tiny lantern");
  await openCreationOptions(page);
  await page.getByRole("button",{name:"Reset optional choices",exact:true}).click();
  await expect(page.getByLabel("What would you like to express?",{exact:true})).toHaveValue("An original design for Sherlock Holmes celebrating.");
  await expect(page.getByLabel("Requested output",{exact:true})).toHaveValue("gif");
  await expect(page.getByLabel("Creative description",{exact:true})).toHaveValue("");
  await expect(page.getByLabel("Expression style",{exact:true})).toHaveValue("auto");
  await expect(page.getByLabel("Expression intensity",{exact:true})).toHaveValue("auto");
  await expect(summary).not.toContainText("Keep a tiny lantern");await expect(summary).toContainText("Saved speaker preferences");
  await page.getByLabel("Requested output",{exact:true}).selectOption("image");
  await page.getByRole("button",{name:"Generate image",exact:true}).click();
  await expect(page.getByText("Output ready for your inspection",{exact:true})).toBeVisible();
  expect(imageBodies).toHaveLength(1);
  expect(imageBodies[0]).not.toContain("Keep a tiny lantern");expect(imageBodies[0]).not.toContain("deadpan-animal");
  expect(imageBodies[0]).toContain("Gentle humor");
});
test("direct UI removes billing text in both languages and wires profile/style to actual image request",async({page})=>{
  await open(page);await openCreate(page);
  await page.locator(".speaker-profile summary").click();
  await page.getByLabel("Profile language",{exact:true}).selectOption("zh-CN");
  await page.getByLabel("Speaker tone",{exact:true}).fill("Restrained workplace thanks");
  await expect(page.getByRole("button",{name:"Generate image",exact:true})).toBeDisabled();
  await page.getByRole("button",{name:"Save speaker profile",exact:true}).click();
  await expect(page.locator(".speaker-profile summary")).toContainText("self-reported");
  await page.getByLabel("What would you like to express?",{exact:true}).fill("Thank a fictional teammate for patiently helping.");
  await page.getByLabel("Creative description",{exact:true}).fill("One original gardener character, hand on heart and a small warm smile.");
  await page.getByLabel("Expression style",{exact:true}).selectOption("playful-doodle");
  await page.getByLabel("Expression intensity",{exact:true}).selectOption("restrained");
  const reviewed=page.waitForResponse(r=>new URL(r.url()).pathname==="/local/generation/review");
  await page.getByRole("button",{name:"Generate image",exact:true}).click();
  const exact=(await (await reviewed).json()).body;
  await expect(page.getByRole("region",{name:"Creation confirmation"})).toHaveCount(0);
  await expect(page.getByRole("button",{name:"Confirm creative idea",exact:true})).toHaveCount(0);
  expect(exact).toContain("Restrained workplace thanks");expect(exact).toContain("playful-doodle");
  expect(await page.locator("body").innerText()).not.toMatch(/billed|billing|paid request|计费|付费/iu);
  await expect(page.getByText("Output ready for your inspection",{exact:true})).toBeVisible();
  expect(imageBodies).toEqual([exact]);
  await page.getByRole("button",{name:"Preview generated insertion",exact:true}).click();
  await page.getByRole("button",{name:"Insert generated visual locally",exact:true}).click();
  await expect(page.getByTestId("chat-message")).toHaveCount(1);
  await page.getByLabel("Language / 语言").selectOption("zh-CN");
  await openCreate(page,"zh-CN");
  expect(await page.locator("body").innerText()).not.toMatch(/billed|billing|paid request|计费|付费/iu);
  await page.setViewportSize({width:320,height:900});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  expect(imageBodies).toHaveLength(1);
});
test("selected sender and outgoing speaker reports reach separate actual analysis requests; profile edits and removal invalidate old reviews",async({page})=>{
  await open(page);
  await api(page,"speaker/profile",{speaker:"Maya",profile:{...emptySpeakerProfile(),language:"zh-CN",tone:"Understated thanks"}});
  await api(page,"speaker/profile",{speaker:"Alex",profile:{...emptySpeakerProfile(),language:"en",humor:"Gentle deadpan"}});
  const bytes=await sharp({create:{width:32,height:32,channels:3,background:"#426ca5"}}).png().toBuffer();
  await api(page,"message",{speaker:"Maya",text:"Thanks for the fictional prototype help.",attachment:{base64:bytes.toString("base64"),mime:"image/png",category:"image"}});
  await page.reload();await page.getByLabel("Language / 语言").selectOption("en");
  await page.getByTestId("chat-message").getByRole("button",{name:"Explain",exact:true}).click();
  await expect(page.locator(".speaker-profile summary")).toContainText("Maya");
  await expect.poll(()=>analysisInputs.length).toBe(1);
  await expect(page.getByRole("heading",{name:"Possible meaning",exact:true})).toBeVisible();
  expect(analysisInputs[0].speakerContext).toMatchObject({role:"selected-sender",profile:{tone:"Understated thanks"}});
  await page.getByRole("button",{name:"Express",exact:true}).click();
  await expect(page.locator(".speaker-profile summary")).toContainText("Alex");
  await page.getByLabel("What would you like to express?",{exact:true}).fill("Reply with a friendly understated reaction.");
  await page.getByRole("button",{name:"Review selected content",exact:true}).click();
  await page.getByRole("button",{name:"Recommend expressions",exact:true}).click();
  await expect(page.locator(".local-candidate")).toHaveCount(3);
  expect(analysisInputs[1].speakerContext).toMatchObject({role:"outgoing-speaker",profile:{humor:"Gentle deadpan"}});
  await page.getByRole("button",{name:"New review",exact:true}).click();
  await page.getByRole("button",{name:"Review selected content",exact:true}).click();
  await page.locator(".speaker-profile summary").click();
  await page.getByLabel("Speaker humor",{exact:true}).fill("No sarcasm");
  await expect(page.getByRole("region",{name:"Content confirmation"})).toHaveCount(0);
  await page.getByRole("button",{name:"Save speaker profile",exact:true}).click();
  await expect(page.getByRole("button",{name:"Remove speaker profile",exact:true})).toBeEnabled();
  await page.getByRole("button",{name:"Remove speaker profile",exact:true}).click();
  await expect(page.locator(".speaker-profile summary")).toContainText("unknown");
  await expect(page.getByTestId("chat-message")).toHaveCount(1);
});
test("server-bound culture ignores names, differs by explicit report, invalidates generation on switch, isolates owners and resets profiles",async({page,browser})=>{
  await open(page);
  const draft={intent:"Thank a fictional teammate.",creative:"One original expressive gardener.",output:"image",context:[],
    preferences:{source:"requester-reported",language:"en",culture:"",familiarity:"",tone:"",relationship:"",humor:"",avoid:""},
    expression:{style:"reaction-sticker",intensity:"restrained",reference:""}};
  const profile={...emptySpeakerProfile(),tone:"Quiet appreciation"};
  await api(page,"speaker/profile",{speaker:"A",profile});await api(page,"speaker/profile",{speaker:"B",profile});
  await api(page,"speaker",{speaker:"A"});
  const a=(await api(page,"generation/review",{draft,draftRevision:1})).value;
  await api(page,"speaker",{speaker:"B"});
  const stale=await api(page,"generation/process",{operationId:a.operationId,digest:a.digest,consent:true});
  expect(stale.value.status).not.toBe("ready");expect(imageBodies).toHaveLength(0);
  const b=(await api(page,"generation/review",{draft,draftRevision:2})).value;expect(a.body).toBe(b.body);
  await api(page,"speaker/profile",{speaker:"B",profile:{...profile,humor:"Playful deadpan"}});
  const changed=(await api(page,"generation/review",{draft,draftRevision:3})).value;expect(changed.body).not.toBe(b.body);
  await api(page,"speaker/profile",{speaker:"B",profile:null});
  const unknown=(await api(page,"generation/review",{draft,draftRevision:4})).value;expect(unknown.prompt).toContain('"profile":null');
  const foreign=await browser.newContext(),other=await foreign.newPage();await other.goto(origin+"/chat");
  expect((await api(other,"state")).value.speakerProfiles).toEqual([]);
  expect((await api(other,"generation/status",{operationId:unknown.operationId})).status).toBe(400);await foreign.close();
  expect((await api(page,"speaker/profile",{speaker:"A",profile:{...profile,inferredNationality:"no"}})).status).toBe(400);
  expect((await api(page,"generation/review",{draft:{...draft,speakerContext:{profile}},draftRevision:5})).status).toBe(400);
  await api(page,"reset");expect((await api(page,"state")).value.speakerProfiles).toEqual([]);
});
test("changing the outgoing speaker during internal review cancels the clicked request before dispatch",async({page})=>{
  await open(page);await openCreate(page);
  await page.getByLabel("What would you like to express?",{exact:true}).fill("An original warm greeting.");
  const held=await holdCreationReview(page);
  await page.getByRole("button",{name:"Generate image",exact:true}).click();
  await held.review;
  await page.getByLabel("Simulated speaker",{exact:true}).fill("Maya");
  await expect(page.getByRole("region",{name:"Creation confirmation"})).toHaveCount(0);
  await expect(page.locator(".speaker-profile summary")).toContainText("Maya");
  await expect.poll(async()=> (await api(page,"state")).value.outgoingSpeaker).toBe("Maya");
  await held.release();
  await expect(page.getByRole("button",{name:"Generate image",exact:true})).toBeEnabled();
  expect(imageBodies).toHaveLength(0);
});
test("one-use review hold preserves fallback precedence and immediate follow-up dispatch",async({page})=>{
  let reviews=0,processes=0,fallbacks=0;
  const server=createServer((req,res)=>{
    if(req.url==="/local/generation/review")reviews++;
    if(req.url==="/local/generation/process")processes++;
    res.writeHead(200,{"Content-Type":"application/json"});
    res.end(JSON.stringify({synthetic:true}));
  });
  await new Promise<void>(resolve=>server.listen(0,"127.0.0.1",resolve));
  try{
    await page.goto(`http://127.0.0.1:${(server.address() as AddressInfo).port}`);
    await page.route("**/local/generation/review",async route=>{fallbacks++;await route.continue();});
    const held=await holdCreationReview(page);
    const first=page.evaluate(async()=>{
      await fetch("/local/generation/review",{method:"POST"});
      return (await fetch("/local/generation/process",{method:"POST"})).status;
    });
    await held.review;
    expect(processes).toBe(0);expect(fallbacks).toBe(0);
    expect(await page.evaluate(async()=>(await fetch("/local/generation/review",{method:"POST"})).status)).toBe(200);
    expect(fallbacks).toBe(1);expect(processes).toBe(0);
    await held.release();
    expect(await first).toBe(200);expect(processes).toBe(1);
    expect(await page.evaluate(async()=>(await fetch("/local/generation/review",{method:"POST"})).status)).toBe(200);
    expect(fallbacks).toBe(2);expect(reviews).toBe(3);
  }finally{
    await page.close();
    await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));
  }
});
for(const language of ["en","zh-CN"] as const)test(`clean ${language} single click preserves exact reviewed request and user choices without a confirmation card`,async({page})=>{
  const t=(en:string,zh:string)=>language==="en"?en:zh;
  await open(page);
  await api(page,"message",{speaker:"Maya",text:"A fictional colleague stayed to help. 😂"});
  await api(page,"speaker/profile",{speaker:"Alex",profile:{...emptySpeakerProfile(),language,tone:"Gentle gratitude"}});
  await page.reload();await page.getByLabel("Language / 语言").selectOption(language);
  const clean=async()=>{
    const body=await page.locator("body").innerText();
    expect(body).not.toMatch(/aoai-visual-context|your-image-deployment|gpt-image|api-version|personal-image-ongoing|max_tokens|1024|512px|bytes|SHA-256|Model requests|模型请求|内容摘要|目的地（|全部文字与选项/iu);
    await expect(page.locator("pre")).toHaveCount(0);
  };
  await clean();expect(imageBodies).toHaveLength(0);expect(analysisInputs).toHaveLength(0);
  await page.getByTestId("chat-message").getByRole("button",{name:t("Explain","解释一下"),exact:true}).click();
  await expect(page.getByRole("heading",{name:t("Possible meaning","可能的含义"),exact:true})).toBeVisible();
  await page.getByRole("button",{name:t("Edit context / reanalyze","编辑上下文 / 重新分析"),exact:true}).click();
  await page.getByLabel(t("Context 1","上下文 1"),{exact:true}).fill("Only this edited context");
  const analysisResponse=page.waitForResponse(r=>new URL(r.url()).pathname==="/local/review");
  await page.getByRole("button",{name:t("Review selected content","确认所选内容"),exact:true}).click();
  const analysisReview=await (await analysisResponse).json();
  await expect(page.getByRole("region",{name:t("Content confirmation","内容确认")})).toContainText("Only this edited context");
  await clean();
  expect(analysisReview.input.context[0].text).toBe("Only this edited context");
  expect(analysisInputs).toHaveLength(1);
  await page.locator(".local-tabs").getByRole("button",{name:t("Express","帮我表达"),exact:true}).click();
  await page.getByLabel(t("What would you like to express?","你想表达什么？"),{exact:true}).fill("Offer warm thanks");
  await page.getByRole("button",{name:t("Review selected content","确认所选内容"),exact:true}).click();
  const expression=page.getByRole("region",{name:t("Content confirmation","内容确认")});
  await expect(expression).toContainText("Offer warm thanks");await expect(expression).toContainText("Gentle gratitude");
  await clean();expect(analysisInputs).toHaveLength(1);
  await openCreate(page,language);
  await page.getByLabel(t("What would you like to express?","你想表达什么？"),{exact:true}).fill("Thank a fictional colleague");
  await page.getByLabel(t("Creative description","创作描述"),{exact:true}).fill("An original gardener holding a plant");
  await page.getByLabel(t("Expression style","表达风格"),{exact:true}).selectOption("playful-doodle");
  await page.getByLabel(t("Expression intensity","表达强度"),{exact:true}).selectOption("restrained");
  await page.getByText(t("Audience preferences & context","受众偏好与上下文"),{exact:true}).click();
  await page.getByLabel(t("Include context 1","包含上下文 1"),{exact:true}).check();
  await page.getByLabel(t("Context 1","上下文 1"),{exact:true}).fill("Reviewed fictional conversation");
  await page.getByText(t("Culture & style (optional)","文化与风格（可选）"),{exact:true}).click();
  await page.getByLabel(t("Textual reference idea","文字参考灵感"),{exact:true}).fill("Quiet appreciation");
  const held=await holdCreationReview(page);
  await page.getByRole("button",{name:t("Generate image","生成图片"),exact:true}).click();
  const review=await held.review,region=page.getByRole("region",{name:t("Create a new visual","创作新视觉内容")});
  for(const value of ["Thank a fictional colleague","An original gardener holding a plant","Gentle gratitude","Quiet appreciation","Reviewed fictional conversation","playful-doodle","restrained"])
    expect(review.body).toContain(value);
  await expect(page.getByRole("region",{name:t("Creation confirmation","创作确认")})).toHaveCount(0);
  await expect(page.getByRole("button",{name:t("Confirm creative idea","确认创作内容"),exact:true})).toHaveCount(0);
  expect(review.digest).toMatch(/^[A-Za-z0-9_-]{43}$/);
  expect(review.bodyBytes).toBe(Buffer.byteLength(review.body));
  expect(review.body).toContain("Reviewed fictional conversation");
  expect(review.body).toContain("playful-doodle");
  await clean();
  expect(review.destination).toBeDefined();
  for(const backend of [review.profileVersion,review.digest,...Object.values(review.destination??{})])expect(await region.innerText()).not.toContain(backend);
  expect(imageBodies).toHaveLength(0);
  expect((await api(page,"generation/process",{operationId:review.operationId,digest:"tampered",consent:true})).status).toBe(400);
  expect((await api(page,"generation/process",{operationId:review.operationId,digest:review.digest,consent:false})).status).toBe(400);
  expect(imageBodies).toHaveLength(0);
  const directory=resolve(".local","visual-context","oneclick-create-validation");await mkdir(directory,{recursive:true});
  await region.scrollIntoViewIfNeeded();await page.screenshot({path:resolve(directory,`${language}-mock-desktop.png`)});
  await page.setViewportSize({width:320,height:900});await region.scrollIntoViewIfNeeded();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  await page.screenshot({path:resolve(directory,`${language}-mock-mobile.png`)});
  const dispatched=page.waitForRequest(r=>new URL(r.url()).pathname==="/local/generation/process");
  const completed=page.waitForResponse(r=>new URL(r.url()).pathname==="/local/generation/process");
  await held.release();
  expect((await dispatched).postDataJSON()).toEqual({operationId:review.operationId,digest:review.digest,consent:true});
  const response=await completed;expect(response.status()).toBe(200);
  expect(await response.json()).toMatchObject({status:"ready",operationId:review.operationId,digest:review.digest});
  await expect(page.getByText(t("Output ready for your inspection","输出等待你检查"),{exact:true})).toBeVisible();
  expect(imageBodies).toEqual([review.body]);await clean();
  await page.getByRole("button",{name:t("Preview generated insertion","预览生成内容插入"),exact:true}).click();
  await clean();
  await page.getByRole("button",{name:t("Insert generated visual locally","将生成内容插入本地"),exact:true}).click();
  await page.setViewportSize({width:1440,height:900});
  await expect(page.getByTestId("chat-message")).toHaveCount(2);await clean();
  expect(imageBodies).toHaveLength(1);
});
for(const language of ["en","zh-CN"] as const)test(`unified ${language} expression keeps one intent/context across modes and dispatches only the chosen provider`,async({page})=>{
  const t=(en:string,zh:string)=>language==="en"?en:zh;
  await open(page);
  await api(page,"message",{speaker:"Maya",text:"Fictional help"});
  await api(page,"message",{speaker:"Leo",text:"EXCLUDED_CONTEXT"});
  await api(page,"speaker/profile",{speaker:"Alex",profile:{...emptySpeakerProfile(),tone:"Outgoing quiet thanks"}});
  await page.reload();await page.getByLabel("Language / 语言").selectOption(language);
  await expect(page.locator(".local-tabs button")).toHaveText([t("Explain","解释含义"),t("Express","帮我表达")]);
  await expect(page.locator(".local-composer .studio-composer-ai")).toHaveCount(1);
  await page.locator(".local-composer").getByRole("button",{name:t("Help me express","帮我表达"),exact:true}).click();
  const intent=page.getByLabel(t("What would you like to express?","你想表达什么？"),{exact:true});
  const existing=page.getByRole("radio",{name:t("Find an existing image","推荐现成图"),exact:true}),create=page.getByRole("radio",{name:t("Create a new image","生成新图"),exact:true});
  await expect(existing).toBeChecked();await expect(intent).toHaveCount(1);await intent.fill("  谢谢你耐心帮忙 🙂  ");
  await page.getByText(t("Audience preferences & context","受众偏好与上下文"),{exact:true}).click();
  await page.getByLabel(t("Context 1","上下文 1"),{exact:true}).fill("Reviewed shared context");
  await page.getByLabel(t("Include context 2","包含上下文 2"),{exact:true}).uncheck();
  await page.getByLabel(t("Tone preference","语气偏好"),{exact:true}).selectOption("casual");
  await page.getByLabel(t("Avoid","避免内容"),{exact:true}).fill("No sarcasm");
  await existing.focus();await page.keyboard.press("ArrowRight");
  await expect(create).toBeChecked();await expect(create).toBeFocused();
  await openCreationOptions(page);
  await page.getByText(t("Audience preferences & context","受众偏好与上下文"),{exact:true}).click();
  await expect(intent).toHaveValue("  谢谢你耐心帮忙 🙂  ");
  await page.getByLabel(t("Creative description","创作描述"),{exact:true}).fill("An original thoughtful owl");
  const held=await holdCreationReview(page);
  await page.getByRole("button",{name:t("Generate image","生成图片"),exact:true}).click();
  const obsolete=await held.review;
  expect(imageBodies).toHaveLength(0);expect(analysisInputs).toHaveLength(0);
  await page.getByLabel(t("Context 1","上下文 1"),{exact:true}).fill("Changed shared context");
  await expect(page.getByRole("region",{name:t("Creation confirmation","创作确认")})).toHaveCount(0);
  await page.getByLabel(t("Context 1","上下文 1"),{exact:true}).fill("Reviewed shared context");
  await existing.check();await expect(page.getByRole("region",{name:t("Creation confirmation","创作确认")})).toHaveCount(0);
  await held.release();
  await expect(intent).toHaveValue("  谢谢你耐心帮忙 🙂  ");
  await expect(page.getByLabel(t("Context 1","上下文 1"),{exact:true})).toHaveValue("Reviewed shared context");
  await expect(page.getByLabel(t("Include context 2","包含上下文 2"),{exact:true})).not.toBeChecked();
  const stale=await api(page,"generation/process",{operationId:obsolete.operationId,digest:obsolete.digest,consent:true});
  expect(stale.value.status).not.toBe("ready");
  expect(imageBodies).toHaveLength(0);expect(app.memeCounters.metadataRequests).toBe(0);
  await page.getByRole("button",{name:t("Review selected content","确认所选内容"),exact:true}).click();
  await page.getByRole("button",{name:t("Recommend expressions","推荐表情"),exact:true}).click();
  await expect(page.locator(".local-candidate")).toHaveCount(3);
  expect(analysisInputs).toHaveLength(1);expect(imageBodies).toHaveLength(0);
  expect(analysisInputs[0]).toMatchObject({intent:"  谢谢你耐心帮忙 🙂  ",frames:[],speakerContext:{role:"outgoing-speaker",profile:{tone:"Outgoing quiet thanks"}}});
  expect(JSON.stringify(analysisInputs[0])).toContain("Reviewed shared context");expect(JSON.stringify(analysisInputs[0])).not.toContain("EXCLUDED_CONTEXT");
  await page.getByRole("button",{name:t("Preview insertion","预览插入"),exact:true}).first().click();
  await page.getByRole("button",{name:t("Insert into local chat","插入本地对话"),exact:true}).click();
  await expect(page.getByTestId("chat-message")).toHaveCount(3);
  await create.check();await expect(intent).toHaveValue("  谢谢你耐心帮忙 🙂  ");
  await expect(page.getByLabel(t("Creative description","创作描述"),{exact:true})).toHaveValue("An original thoughtful owl");
  await expect(page.locator(".local-candidate")).toHaveCount(0);
  const reviewed=page.waitForResponse(r=>new URL(r.url()).pathname==="/local/generation/review");
  await page.getByRole("button",{name:t("Generate image","生成图片"),exact:true}).click();
  const review=await (await reviewed).json();
  expect(review.body).toContain("Reviewed shared context");expect(review.body).toContain("No sarcasm");expect(review.body).toContain("Outgoing quiet thanks");
  expect(review.body).not.toContain("EXCLUDED_CONTEXT");
  await page.setViewportSize({width:320,height:900});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  expect((await create.boundingBox())!.width).toBeLessThanOrEqual(24);
  const directory=resolve(".local","visual-context","unified-express-validation");await mkdir(directory,{recursive:true});
  await page.getByRole("region",{name:t("Your expression","你的表达")}).scrollIntoViewIfNeeded();
  await page.screenshot({path:resolve(directory,`${language}-mock-mobile.png`)});
  await expect(page.getByText(t("Output ready for your inspection","输出等待你检查"),{exact:true})).toBeVisible();
  expect(imageBodies).toEqual([review.body]);expect(analysisInputs).toHaveLength(1);
  await page.getByRole("button",{name:t("Preview generated insertion","预览生成内容插入"),exact:true}).click();
  await page.getByRole("button",{name:t("Insert generated visual locally","将生成内容插入本地"),exact:true}).click();
  await page.setViewportSize({width:1440,height:900});await expect(page.getByTestId("chat-message")).toHaveCount(4);
});
test("mode switching cancels a held image request without releasing its lease or showing its late result",async({page})=>{
  await open(page);await openCreate(page);holdImage=true;
  await page.getByLabel("What would you like to express?",{exact:true}).fill("An original friendly owl");
  await page.getByRole("button",{name:"Generate image",exact:true}).click();
  await expect.poll(()=>imageBodies.length).toBe(1);
  await page.getByRole("radio",{name:"Find an existing image",exact:true}).check();
  await expect(page.getByRole("region",{name:"Generation operation"})).toHaveCount(0);
  const {localPaidLease}=await import(built("local-generation-config.js"));expect(localPaidLease.busy).toBe(true);
  await page.getByRole("button",{name:"Review selected content",exact:true}).click();
  expect(analysisInputs).toHaveLength(0);expect(imageBodies).toHaveLength(1);
  const blocked=await api(page,"review",{command:"recommendVisual",input:{
    version:0,intent:"A safe fictional reply",context:[],preferences:{source:"requester-reported",confirmed:true,outputLanguage:"en",familiarity:"",formality:"unknown",relationship:"",humor:"",avoid:""}
  }});
  expect(blocked.status).toBe(400);expect(blocked.value.code).toBe("processing-review-required");
  expect(analysisInputs).toHaveLength(0);expect(localPaidLease.busy).toBe(true);
  releaseImage?.();await expect.poll(()=>localPaidLease.busy).toBe(false);
  await expect(page.getByRole("region",{name:"Generation operation"})).toHaveCount(0);
  await expect(page.getByRole("button",{name:"Insert generated visual locally",exact:true})).toHaveCount(0);
});
test("shared contexts exceeding the generation contract are rejected explicitly, not silently shortened",async({page})=>{
  await open(page);
  for(let i=0;i<5;i++)await api(page,"message",{speaker:"Maya",text:"x".repeat(1800)});
  await page.reload();await page.getByLabel("Language / 语言").selectOption("en");
  await openCreate(page);
  await page.getByLabel("What would you like to express?",{exact:true}).fill("A fictional thank-you");
  await page.getByRole("button",{name:"Generate image",exact:true}).click();
  await expect(page.getByRole("alert")).toContainText("too much content for one request");
  expect(imageBodies).toHaveLength(0);expect(analysisInputs).toHaveLength(0);
  await page.getByText("Audience preferences & context",{exact:true}).click();
  for(let i=1;i<=5;i++)await expect(page.getByLabel(`Context ${i}`,{exact:true})).toHaveValue("Maya: "+"x".repeat(1800));
});
for(const language of ["en","zh-CN"] as const)test(`one ${language} Generate GIF click reviews, generates and animates without a second confirmation`,async({page})=>{
  const t=(en:string,zh:string)=>language==="en"?en:zh;
  await open(page);await page.getByLabel("Language / 语言").selectOption(language);await openCreate(page,language);
  await page.getByLabel(t("What would you like to express?","你想表达什么？"),{exact:true}).fill("A fictional gentle owl greeting");
  await page.getByLabel(t("Requested output","期望输出"),{exact:true}).selectOption("gif");
  await expect(page.getByRole("button",{name:t("Generate image","生成图片"),exact:true})).toHaveCount(0);
  const response=page.waitForResponse(r=>new URL(r.url()).pathname==="/local/generation/review");
  await page.getByRole("button",{name:t("Generate GIF","生成 GIF"),exact:true}).click();
  const review=await (await response).json();expect(review.output).toBe("gif");
  await expect(page.getByText(t("Output ready for your inspection","输出等待你检查"),{exact:true})).toBeVisible();
  await expect(page.getByRole("button",{name:t("Use local GIF","使用本地 GIF"),exact:true})).toHaveAttribute("aria-pressed","true");
  await expect(page.getByRole("region",{name:t("Creation confirmation","创作确认")})).toHaveCount(0);
  expect(imageBodies).toEqual([review.body]);await expect(page.getByTestId("chat-message")).toHaveCount(0);
  await page.getByRole("button",{name:t("Preview generated insertion","预览生成内容插入"),exact:true}).click();
  await page.getByRole("button",{name:t("Insert generated visual locally","将生成内容插入本地"),exact:true}).click();
  await expect(page.getByTestId("chat-message")).toHaveCount(1);expect(imageBodies).toHaveLength(1);
});
test("Cancel generation during internal preparation prevents dispatch and permits a fresh explicit click",async({page})=>{
  await open(page);await openCreate(page);
  await page.getByLabel("What would you like to express?",{exact:true}).fill("A fictional thank-you");
  const held=await holdCreationReview(page);
  await page.getByRole("button",{name:"Generate image",exact:true}).click();const obsolete=await held.review;
  await page.getByRole("button",{name:"Cancel generation",exact:true}).click();await held.release();
  expect((await api(page,"generation/process",{operationId:obsolete.operationId,digest:obsolete.digest,consent:true})).value.status).not.toBe("ready");
  expect(imageBodies).toHaveLength(0);
  await page.getByRole("button",{name:"Generate image",exact:true}).click();
  await expect(page.getByText("Output ready for your inspection",{exact:true})).toBeVisible();expect(imageBodies).toHaveLength(1);
});
test("provider failure never retries automatically and a new explicit click can retry",async({page})=>{
  await open(page);await openCreate(page);failImage=true;
  await page.getByLabel("What would you like to express?",{exact:true}).fill("A fictional thanks");
  await page.getByRole("button",{name:"Generate image",exact:true}).click();
  await expect(page.getByText("Generation failed. No automatic retry.",{exact:true})).toBeVisible();
  await page.getByRole("button",{name:"Hide AI panel",exact:true}).click();
  await page.getByRole("button",{name:"Open AI panel",exact:true}).click();
  await expect(page.getByRole("button",{name:"Generate image",exact:true})).toBeEnabled();
  expect(imageBodies).toHaveLength(1);failImage=false;
  await page.getByRole("button",{name:"Generate image",exact:true}).click();
  await expect(page.getByText("Output ready for your inspection",{exact:true})).toBeVisible();expect(imageBodies).toHaveLength(2);
});
test("lost process response preserves the known operation across hiding; status lookup never redispatches",async({page})=>{
  await open(page);await openCreate(page);
  await page.getByLabel("What would you like to express?",{exact:true}).fill("A fictional quiet welcome");
  await page.route("**/local/generation/process",async route=>{await route.fetch();await route.abort("failed");});
  await page.getByRole("button",{name:"Generate image",exact:true}).click();
  await expect(page.getByText("Completion is uncertain. Check this operation's status; do not resubmit it.",{exact:true})).toBeVisible();
  await expect(page.getByRole("button",{name:"Generate image",exact:true})).toBeDisabled();
  await page.getByRole("button",{name:"Hide AI panel",exact:true}).click();
  await page.getByRole("button",{name:"Open AI panel",exact:true}).click();
  await page.getByRole("button",{name:"Check known operation status",exact:true}).click();
  await expect(page.getByText("Output ready for your inspection",{exact:true})).toBeVisible();
  expect(imageBodies).toHaveLength(1);
  await page.getByRole("button",{name:"Preview generated insertion",exact:true}).click();
  await page.getByRole("button",{name:"Insert generated visual locally",exact:true}).click();
  await expect(page.getByTestId("chat-message")).toHaveCount(1);expect(imageBodies).toHaveLength(1);
});
test("failed cancellation while replacing a result stops the one-click chain before another provider call",async({page})=>{
  await open(page);await openCreate(page);
  await page.getByLabel("What would you like to express?",{exact:true}).fill("A fictional welcome");
  await page.getByRole("button",{name:"Generate image",exact:true}).click();
  await expect(page.getByText("Output ready for your inspection",{exact:true})).toBeVisible();
  await page.route("**/local/cancel",route=>route.fulfill({status:503,json:{code:"generation-provider-unavailable"}}));
  await page.getByRole("button",{name:"Generate image",exact:true}).click();
  await expect(page.getByRole("alert")).toBeVisible();
  await expect(page.getByRole("button",{name:"Generate image",exact:true})).toBeEnabled();
  expect(imageBodies).toHaveLength(1);
  await page.unroute("**/local/cancel");
  await page.getByRole("button",{name:"Generate image",exact:true}).click();
  await expect(page.getByText("Output ready for your inspection",{exact:true})).toBeVisible();expect(imageBodies).toHaveLength(2);
});
